# -*- coding: utf-8 -*-
"""BGC_Classfication.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Fib7p4lpPfCzybPMPq92-3ilKikvf3f
"""

#Main Code

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
TRANSFORMER PIPELINE: BGC/NON-BGC SEPARATION + BGC CLASSIFICATION
---------------------------------------------------------------
1. General Transformer: BGC vs Non-BGC classification
2. BGC-Class Transformer: Classifies BGC types (only for BGC samples)
3. Only transformer features used (original features not included)
4. WITH FFN LAYERS AFTER MHA
5. MEMORY OPTIMIZED VERSION
6. EARLY STOPPING ENABLED
"""

import os
import gc
import numpy as np
import pandas as pd
import joblib
import warnings
warnings.filterwarnings('ignore')

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

import tensorflow as tf
from tensorflow.keras.layers import (
    Input, Dense, MultiHeadAttention, LayerNormalization,
    Dropout, GlobalAveragePooling1D, GlobalMaxPooling1D, Reshape,
    Concatenate, Add, AveragePooling1D
)
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
import tensorflow.keras.backend as K

# ============================
# CONFIGURATION
# ============================
FILE = "/home/andromeda_r740/MB/final_output.csv"
MODEL_SAVE_DIR = "/home/andromeda_r740/MB/PRETRAINED_TRANSFORMERS_BGC"
OUTPUT_DIR = "/home/andromeda_r740/MB/TRAINING_OUTPUT"

os.makedirs(MODEL_SAVE_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Force CPU for stability
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

# PARAMETERS
TEST_SIZE = 0.20
VAL_SIZE = 0.10
RANDOM_STATE = 42
BATCH_SIZE = 128  # Reduced batch size
MAX_EPOCHS = 100  # Increased to 100 with early stopping
PATIENCE = 10     # Slightly increased patience for 100 epochs
MIN_DELTA = 0.001 # Minimum change to qualify as improvement

# ARCHITECTURE CONFIG - MEMORY OPTIMIZED
BGC_GENERAL_CONFIG = {
    'input_dim': None,
    'embed_dim': 32,      # Reduced from 64
    'num_heads': 4,       # Reduced from 4
    'ff_dim': 32,         # Reduced from 128
    'dropout_rate': 0.2,
    'pool_size': 4,       # Pooling to reduce sequence length
    'output_features': 1024, # Reduced from 256
    'learning_rate': 0.001
}

BGC_CLASS_CONFIG = {
    'input_dim': None,
    'embed_dim': 16,      # Reduced from 64
    'num_heads': 2,       # Reduced from 4
    'ff_dim': 32,         # Reduced from 128
    'dropout_rate': 0.2,
    'pool_size': 4,       # Pooling to reduce sequence length
    'output_features': 512, # Reduced from 128
    'learning_rate': 0.001
}

# ============================
# 1. MEMORY MANAGEMENT
# ============================
def clear_memory():
    K.clear_session()
    gc.collect()

# ============================
# 2. MEMORY-OPTIMIZED TRANSFORMER BUILDERS
# ============================
def build_bgc_general_transformer(config):
    """General transformer for BGC vs Non-BGC classification with FFN - Memory Optimized"""
    inputs = Input(shape=(config['input_dim'],))

    # Reshape for sequence processing
    x = Reshape((config['input_dim'], 1))(inputs)

    # Initial projection to reduce dimensionality
    x = Dense(config['embed_dim'], activation='relu')(x)
    x = Dropout(config['dropout_rate'])(x)

    # Apply pooling to reduce sequence length
    if config['pool_size'] > 1:
        x = AveragePooling1D(pool_size=config['pool_size'])(x)

    # Multi-head attention with reduced dimensions
    attn_output = MultiHeadAttention(
        num_heads=config['num_heads'],
        key_dim=config['embed_dim'] // config['num_heads']
    )(x, x)

    # Add & Norm
    x = Add()([x, attn_output])
    x = LayerNormalization()(x)

    # Feed Forward Network (FFN)
    ffn_output = Dense(config['ff_dim'], activation='relu')(x)
    ffn_output = Dropout(config['dropout_rate'])(ffn_output)
    ffn_output = Dense(config['embed_dim'])(ffn_output)

    # Add & Norm
    x = Add()([x, ffn_output])
    x = LayerNormalization()(x)

    # Dual pooling
    avg_pool = GlobalAveragePooling1D()(x)
    max_pool = GlobalMaxPooling1D()(x)
    x_combined = Concatenate(name='feature_layer')([avg_pool, max_pool])
    x_combined = Dropout(config['dropout_rate'])(x_combined)

    # Feature output
    features = Dense(config['output_features'], activation='relu', name='bgc_features')(x_combined)

    # Binary output (BGC vs Non-BGC)
    binary_output = Dense(1, activation='sigmoid', name='bgc_binary')(features)

    model = Model(inputs=inputs, outputs=[features, binary_output],
                  name='bgc_general_transformer')

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=config['learning_rate']),
        loss={
            'bgc_features': 'mse',
            'bgc_binary': 'binary_crossentropy'
        },
        loss_weights={'bgc_features': 0.2, 'bgc_binary': 0.8},  # Emphasize classification
        metrics={'bgc_binary': ['accuracy', 'AUC']}
    )

    return model

def build_bgc_class_transformer(config, class_name):
    """Transformer for specific BGC class classification with FFN - Memory Optimized"""
    inputs = Input(shape=(config['input_dim'],))

    # Reshape
    x = Reshape((config['input_dim'], 1))(inputs)

    # Initial projection
    x = Dense(config['embed_dim'], activation='relu')(x)
    x = Dropout(config['dropout_rate'])(x)

    # Apply pooling to reduce sequence length
    if config['pool_size'] > 1:
        x = AveragePooling1D(pool_size=config['pool_size'])(x)

    # Multi-head attention with reduced dimensions
    attn_output = MultiHeadAttention(
        num_heads=config['num_heads'],
        key_dim=config['embed_dim'] // config['num_heads']
    )(x, x)

    # Add & Norm
    x = Add()([x, attn_output])
    x = LayerNormalization()(x)

    # Feed Forward Network (FFN)
    ffn_output = Dense(config['ff_dim'], activation='relu')(x)
    ffn_output = Dropout(config['dropout_rate'])(ffn_output)
    ffn_output = Dense(config['embed_dim'])(ffn_output)

    # Add & Norm
    x = Add()([x, ffn_output])
    x = LayerNormalization()(x)

    # Pooling
    avg_pool = GlobalAveragePooling1D()(x)
    max_pool = GlobalMaxPooling1D()(x)
    x_pooled = Concatenate()([avg_pool, max_pool])
    x_pooled = Dropout(config['dropout_rate'])(x_pooled)

    # Feature output
    features = Dense(config['output_features'], activation='relu',
                     name='class_features')(x_pooled)

    # Binary output for this BGC class
    binary_output = Dense(1, activation='sigmoid', name='class_binary')(features)

    model = Model(inputs=inputs, outputs=[features, binary_output],
                  name=f'bgc_class_transformer_{class_name}')

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=config['learning_rate']),
        loss={
            'class_features': 'mse',
            'class_binary': 'binary_crossentropy'
        },
        loss_weights={'class_features': 0.2, 'class_binary': 0.8},
        metrics={'class_binary': ['accuracy', 'AUC']}
    )

    return model

# ============================
# 3. TRAINING FUNCTIONS
# ============================
def train_bgc_general_transformer(X_train, y_train_binary, X_val, y_val_binary, config):
    """Train the general BGC vs non-BGC transformer"""
    print(f"\n⚡ Training BGC General Transformer...")
    print(f"   Training samples: {len(X_train)}")
    print(f"   Validation samples: {len(X_val)}")
    print(f"   Architecture: Input={X_train.shape[1]}, Embed={config['embed_dim']}, FFN={config['ff_dim']}")
    print(f"   Epochs: {MAX_EPOCHS} (Early stopping: patience={PATIENCE}, min_delta={MIN_DELTA})")

    config['input_dim'] = X_train.shape[1]
    model = build_bgc_general_transformer(config)

    # Create feature targets
    y_train_features = np.zeros((len(y_train_binary), config['output_features']))
    y_val_features = np.zeros((len(y_val_binary), config['output_features']))

    # Set features for BGC samples (non-BGC remains zeros)
    y_train_features[y_train_binary == 1] = 1.0
    y_val_features[y_val_binary == 1] = 1.0

    # Enhanced Callbacks with Early Stopping
    callbacks = [
        EarlyStopping(
            monitor='val_bgc_binary_loss',
            patience=PATIENCE,
            min_delta=MIN_DELTA,
            restore_best_weights=True,
            verbose=1,
            mode='min'
        ),
        ReduceLROnPlateau(
            monitor='val_bgc_binary_loss',
            factor=0.5,
            patience=int(PATIENCE/2),  # More frequent learning rate reduction
            min_lr=1e-6,
            verbose=1,
            mode='min'
        ),
        ModelCheckpoint(
            os.path.join(MODEL_SAVE_DIR, 'best_bgc_general.keras'),
            monitor='val_bgc_binary_loss',
            save_best_only=True,
            verbose=1,
            mode='min'
        ),
        tf.keras.callbacks.TerminateOnNaN(),  # Safety callback
        tf.keras.callbacks.CSVLogger(
            os.path.join(OUTPUT_DIR, 'general_transformer_history.csv'),
            separator=',',
            append=False
        )
    ]

    # Train with gradient accumulation if needed
    print("\n   Starting training...")
    print("   Early stopping will automatically stop training if no improvement for {} epochs".format(PATIENCE))

    history = model.fit(
        X_train, {
            'bgc_features': y_train_features,
            'bgc_binary': y_train_binary
        },
        validation_data=(X_val, {
            'bgc_features': y_val_features,
            'bgc_binary': y_val_binary
        }),
        epochs=MAX_EPOCHS,
        batch_size=BATCH_SIZE,
        callbacks=callbacks,
        verbose=1
    )

    # Save final model
    model_path = os.path.join(MODEL_SAVE_DIR, 'bgc_general_transformer.keras')
    model.save(model_path)

    # Evaluate
    actual_epochs = len(history.history['loss'])
    train_binary_acc = history.history['bgc_binary_accuracy'][-1]
    val_binary_acc = history.history['val_bgc_binary_accuracy'][-1]

    print(f"\n   ✓ Training complete: {actual_epochs}/{MAX_EPOCHS} epochs (early stopping triggered)")
    print(f"   ✓ Training accuracy: {train_binary_acc:.4f}")
    print(f"   ✓ Validation accuracy: {val_binary_acc:.4f}")
    print(f"   ✓ Best validation loss: {min(history.history['val_bgc_binary_loss']):.4f}")
    print(f"   ✓ Model saved: {model_path}")

    # Early stopping statistics
    if actual_epochs < MAX_EPOCHS:
        print(f"   ⏹️  Early stopping triggered at epoch {actual_epochs} (saved {MAX_EPOCHS - actual_epochs} epochs)")

    return model, history

def train_bgc_class_transformer(X_train_bgc, y_train_bgc_class, X_val_bgc,
                               y_val_bgc_class, config, class_name, class_idx):
    """Train class-specific transformer for BGC classification"""
    print(f"\n⚡ Training '{class_name}' BGC Class Transformer...")
    print(f"   Training samples: {len(X_train_bgc)}")
    print(f"   Validation samples: {len(X_val_bgc)}")
    print(f"   Epochs: {MAX_EPOCHS} (Early stopping: patience={PATIENCE}, min_delta={MIN_DELTA})")

    config['input_dim'] = X_train_bgc.shape[1]
    model = build_bgc_class_transformer(config, class_name)

    # Binary labels for this specific class
    y_train_binary = (y_train_bgc_class == class_idx).astype(float)
    y_val_binary = (y_val_bgc_class == class_idx).astype(float)

    # Feature targets
    y_train_features = np.zeros((len(y_train_binary), config['output_features']))
    y_val_features = np.zeros((len(y_val_binary), config['output_features']))
    y_train_features[y_train_binary == 1] = 1.0
    y_val_features[y_val_binary == 1] = 1.0

    # Enhanced Callbacks for class transformers
    callbacks = [
        EarlyStopping(
            monitor='val_class_binary_loss',
            patience=max(5, PATIENCE-3),  # Slightly less patience for class models
            min_delta=MIN_DELTA,
            restore_best_weights=True,
            verbose=1,
            mode='min'
        ),
        ModelCheckpoint(
            os.path.join(MODEL_SAVE_DIR, f'best_bgc_class_{class_name}.keras'),
            monitor='val_class_binary_loss',
            save_best_only=True,
            verbose=1,
            mode='min'
        ),
        tf.keras.callbacks.TerminateOnNaN(),
        tf.keras.callbacks.CSVLogger(
            os.path.join(OUTPUT_DIR, f'class_{class_name}_history.csv'),
            separator=',',
            append=False
        )
    ]

    # Train
    print(f"   Early stopping will automatically stop training if no improvement for {max(5, PATIENCE-3)} epochs")

    history = model.fit(
        X_train_bgc, {
            'class_features': y_train_features,
            'class_binary': y_train_binary
        },
        validation_data=(X_val_bgc, {
            'class_features': y_val_features,
            'class_binary': y_val_binary
        }),
        epochs=MAX_EPOCHS,
        batch_size=BATCH_SIZE,
        callbacks=callbacks,
        verbose=1
    )

    # Save model
    safe_name = str(class_name).replace(' ', '_').replace('/', '_')
    model_path = os.path.join(MODEL_SAVE_DIR, f'bgc_class_transformer_{safe_name}.keras')
    model.save(model_path)

    # Evaluate
    actual_epochs = len(history.history['loss'])
    train_binary_acc = history.history['class_binary_accuracy'][-1]
    val_binary_acc = history.history['val_class_binary_accuracy'][-1]

    print(f"   ✓ Training complete: {actual_epochs}/{MAX_EPOCHS} epochs")
    print(f"   ✓ Training accuracy: {train_binary_acc:.4f}")
    print(f"   ✓ Validation accuracy: {val_binary_acc:.4f}")
    print(f"   ✓ Best validation loss: {min(history.history['val_class_binary_loss']):.4f}")
    print(f"   ✓ Model saved: {model_path}")

    # Early stopping statistics
    if actual_epochs < MAX_EPOCHS:
        print(f"   ⏹️  Early stopping triggered at epoch {actual_epochs} (saved {MAX_EPOCHS - actual_epochs} epochs)")

    return model, history

# ============================
# 4. FEATURE EXTRACTION FUNCTIONS
# ============================
def extract_features(model, X_data, is_class_transformer=False):
    """Extract features from transformer with memory optimization"""
    if is_class_transformer:
        feature_extractor = Model(
            inputs=model.input,
            outputs=model.get_layer('class_features').output
        )
    else:
        feature_extractor = Model(
            inputs=model.input,
            outputs=model.get_layer('bgc_features').output
        )

    # Extract features in smaller batches to avoid memory issues
    batch_size = min(64, len(X_data))
    features = []

    for i in range(0, len(X_data), batch_size):
        batch = X_data[i:i+batch_size]
        batch_features = feature_extractor.predict(batch, verbose=0)
        features.append(batch_features)

    return np.vstack(features)

# ============================
# 5. MAIN PIPELINE
# ============================
def main():
    print("="*80)
    print("TRANSFORMER PIPELINE: BGC/NON-BGC + BGC CLASSIFICATION")
    print("="*80)
    print("MEMORY OPTIMIZED VERSION WITH EARLY STOPPING")
    print("="*80)

    print(f"\n⚙️  Configuration:")
    print(f"   • Max epochs: {MAX_EPOCHS}")
    print(f"   • Batch size: {BATCH_SIZE} (reduced for memory)")
    print(f"   • Early stopping patience: {PATIENCE} epochs")
    print(f"   • Min delta for improvement: {MIN_DELTA}")
    print(f"   • Embedding dimension: {BGC_GENERAL_CONFIG['embed_dim']}")
    print(f"   • Num heads: {BGC_GENERAL_CONFIG['num_heads']}")
    print(f"   • Pooling size: {BGC_GENERAL_CONFIG['pool_size']}")

    clear_memory()

    # 1. Load Data
    print("\n📂 Loading data...")
    start_time = pd.Timestamp.now()

    df = pd.read_csv(FILE)
    label_col = df.columns[-1]
    X = df.drop(columns=[label_col]).values.astype(np.float32)

    # Print shape to understand the input size
    print(f"   Raw data shape: {X.shape}")

    le = LabelEncoder()
    y = le.fit_transform(df[label_col].values)
    class_names = le.classes_
    num_classes = len(class_names)

    print(f"   ✓ Loaded: {X.shape[0]} samples, {X.shape[1]} features")
    print(f"   ✓ Classes: {num_classes}")

    # Display class distribution
    class_counts = np.bincount(y)
    for i, class_name in enumerate(class_names):
        print(f"       {class_name}: {class_counts[i]} samples")

    # Identify non-BGC class (assume it's class 0)
    non_bgc_class = class_names[0]
    bgc_classes = class_names[1:]  # All other classes are BGC
    bgc_class_indices = list(range(1, num_classes))

    print(f"\n   ✓ Non-BGC class: {non_bgc_class}")
    print(f"   ✓ BGC classes: {len(bgc_classes)}")

    # Create binary labels: 0 = non-BGC, 1 = BGC
    y_binary = (y != 0).astype(float)

    # Count BGC vs non-BGC
    non_bgc_count = np.sum(y == 0)
    bgc_count = np.sum(y != 0)
    print(f"   ✓ Non-BGC samples: {non_bgc_count}")
    print(f"   ✓ BGC samples: {bgc_count}")

    # 2. Split Data (Train/Val/Test)
    print("\n📈 Splitting data...")

    X_train_val, X_test, y_train_val, y_test, y_binary_train_val, y_binary_test = train_test_split(
        X, y, y_binary, test_size=TEST_SIZE, stratify=y, random_state=RANDOM_STATE
    )

    X_train, X_val, y_train, y_val, y_binary_train, y_binary_val = train_test_split(
        X_train_val, y_train_val, y_binary_train_val, test_size=VAL_SIZE,
        stratify=y_train_val, random_state=RANDOM_STATE
    )

    print(f"   Training: {X_train.shape[0]} samples")
    print(f"   Validation: {X_val.shape[0]} samples")
    print(f"   Test (held out): {X_test.shape[0]} samples")

    # 3. Scale Data
    print("\n⚙️ Scaling data...")
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_val_scaled = scaler.transform(X_val)
    X_test_scaled = scaler.transform(X_test)

    # Save preprocessing
    joblib.dump(scaler, os.path.join(MODEL_SAVE_DIR, 'scaler.pkl'))
    joblib.dump(le, os.path.join(MODEL_SAVE_DIR, 'label_encoder.pkl'))

    # 4. Train General BGC Transformer
    print("\n" + "="*60)
    print("1. TRAINING BGC GENERAL TRANSFORMER")
    print("="*60)

    gen_start = pd.Timestamp.now()
    general_config = BGC_GENERAL_CONFIG.copy()

    print(f"\n⚠️  Memory optimization note:")
    print(f"   • Input features: {X_train_scaled.shape[1]}")
    print(f"   • After pooling: ~{X_train_scaled.shape[1] // general_config['pool_size']} sequence length")
    print(f"   • Attention matrix size will be ~{(X_train_scaled.shape[1] // general_config['pool_size'])**2:,} elements")

    bgc_general_model, gen_history = train_bgc_general_transformer(
        X_train_scaled, y_binary_train, X_val_scaled, y_binary_val, general_config
    )
    gen_time = (pd.Timestamp.now() - gen_start).total_seconds() / 60
    print(f"\n   ⏱️  Training time: {gen_time:.1f} minutes")

    # Clear memory before next step
    clear_memory()

    # 5. Extract BGC samples for class-specific training
    print("\n" + "="*60)
    print("2. PREPARING BGC SAMPLES FOR CLASS-SPECIFIC TRAINING")
    print("="*60)

    # Get BGC samples from training and validation sets
    bgc_train_mask = (y_train != 0)  # BGC samples in training
    bgc_val_mask = (y_val != 0)      # BGC samples in validation

    X_train_bgc = X_train_scaled[bgc_train_mask]
    y_train_bgc_class = y_train[bgc_train_mask]
    X_val_bgc = X_val_scaled[bgc_val_mask]
    y_val_bgc_class = y_val[bgc_val_mask]

    print(f"   BGC training samples: {len(X_train_bgc)}")
    print(f"   BGC validation samples: {len(X_val_bgc)}")

    # 6. Train BGC Class Transformers
    print("\n" + "="*60)
    print(f"3. TRAINING {len(bgc_classes)} BGC CLASS TRANSFORMERS")
    print("="*60)

    class_transformers = {}
    total_class_time = 0
    early_stopping_counts = []

    for i, (class_name, class_idx) in enumerate(zip(bgc_classes, bgc_class_indices)):
        class_start = pd.Timestamp.now()

        print(f"\n[{i+1}/{len(bgc_classes)}] Class: {class_name} (index: {class_idx})")

        class_config = BGC_CLASS_CONFIG.copy()
        transformer, history = train_bgc_class_transformer(
            X_train_bgc, y_train_bgc_class, X_val_bgc, y_val_bgc_class,
            class_config, class_name, class_idx
        )

        class_transformers[class_name] = transformer
        class_time = (pd.Timestamp.now() - class_start).total_seconds() / 60
        total_class_time += class_time

        # Track early stopping statistics
        actual_epochs = len(history.history['loss'])
        early_stopping_counts.append(MAX_EPOCHS - actual_epochs if actual_epochs < MAX_EPOCHS else 0)

        print(f"   ⏱️  Training time: {class_time:.1f} minutes")
        print(f"   🎯 Epochs trained: {actual_epochs}/{MAX_EPOCHS}")

        # Clear memory between trainings
        clear_memory()

    # Early stopping summary
    if early_stopping_counts:
        avg_saved_epochs = np.mean(early_stopping_counts)
        print(f"\n📊 Early stopping summary for class transformers:")
        print(f"   • Average epochs saved: {avg_saved_epochs:.1f}")
        print(f"   • Models that stopped early: {sum(1 for x in early_stopping_counts if x > 0)}/{len(bgc_classes)}")

    # 7. Extract Features from All Data
    print("\n" + "="*60)
    print("4. EXTRACTING TRANSFORMER FEATURES")
    print("="*60)

    print("\n   Extracting general transformer features...")
    train_gen_features = extract_features(bgc_general_model, X_train_scaled, False)
    val_gen_features = extract_features(bgc_general_model, X_val_scaled, False)
    test_gen_features = extract_features(bgc_general_model, X_test_scaled, False)

    print(f"\n   Extracting class transformer features...")
    train_class_features = {}
    val_class_features = {}
    test_class_features = {}

    for class_name in bgc_classes:
        print(f"   - {class_name}")
        model = class_transformers[class_name]
        train_class_features[class_name] = extract_features(model, X_train_scaled, True)
        val_class_features[class_name] = extract_features(model, X_val_scaled, True)
        test_class_features[class_name] = extract_features(model, X_test_scaled, True)

    # 8. Combine Features (General + All Class Features)
    print("\n🔗 Combining transformer features...")

    def combine_features(gen_features, class_features_dict):
        """Combine general transformer features with all class transformer features"""
        combined = gen_features.copy()

        for class_name, features in class_features_dict.items():
            combined = np.concatenate([combined, features], axis=1)

        return combined

    X_train_combined = combine_features(train_gen_features, train_class_features)
    X_val_combined = combine_features(val_gen_features, val_class_features)
    X_test_combined = combine_features(test_gen_features, test_class_features)

    print(f"   ✓ General transformer features: {train_gen_features.shape[1]}")
    print(f"   ✓ Each class transformer features: {list(train_class_features.values())[0].shape[1]}")
    print(f"   ✓ Total class transformer features: {len(bgc_classes) * list(train_class_features.values())[0].shape[1]}")
    print(f"   ✓ Combined features: {X_train_combined.shape[1]}")

    # 9. Save Everything
    print(f"\n💾 Saving results...")

    # Save combined features
    np.save(os.path.join(OUTPUT_DIR, 'X_train_combined.npy'), X_train_combined)
    np.save(os.path.join(OUTPUT_DIR, 'X_val_combined.npy'), X_val_combined)
    np.save(os.path.join(OUTPUT_DIR, 'X_test_combined.npy'), X_test_combined)
    np.save(os.path.join(OUTPUT_DIR, 'y_train.npy'), y_train)
    np.save(os.path.join(OUTPUT_DIR, 'y_val.npy'), y_val)
    np.save(os.path.join(OUTPUT_DIR, 'y_test.npy'), y_test)
    np.save(os.path.join(OUTPUT_DIR, 'y_train_binary.npy'), y_binary_train)
    np.save(os.path.join(OUTPUT_DIR, 'y_val_binary.npy'), y_binary_val)
    np.save(os.path.join(OUTPUT_DIR, 'y_test_binary.npy'), y_binary_test)

    # Save individual features for analysis
    np.save(os.path.join(OUTPUT_DIR, 'train_gen_features.npy'), train_gen_features)
    np.save(os.path.join(OUTPUT_DIR, 'test_gen_features.npy'), test_gen_features)

    # Save early stopping statistics
    early_stopping_stats = {
        'class_name': bgc_classes,
        'max_epochs': [MAX_EPOCHS] * len(bgc_classes),
        'actual_epochs': [len(class_transformers[cn].history.history.get('loss', [0]))
                          for cn in bgc_classes],
        'epochs_saved': early_stopping_counts
    }

    early_stopping_df = pd.DataFrame(early_stopping_stats)
    early_stopping_df.to_csv(os.path.join(OUTPUT_DIR, 'early_stopping_stats.csv'), index=False)

    # Save metadata
    total_time = (pd.Timestamp.now() - start_time).total_seconds() / 3600

    metadata = {
        'pipeline': 'BGC_Classification_Transformers_MemoryOptimized_EarlyStopping',
        'total_time_hours': round(total_time, 2),
        'general_transformer_time_minutes': round(gen_time, 1),
        'total_class_time_minutes': round(total_class_time, 1),
        'avg_class_time_minutes': round(total_class_time / len(bgc_classes), 1),
        'samples_total': X.shape[0],
        'samples_train': X_train.shape[0],
        'samples_val': X_val.shape[0],
        'samples_test': X_test.shape[0],
        'non_bgc_class': non_bgc_class,
        'num_bgc_classes': len(bgc_classes),
        'original_features': X.shape[1],
        'embedding_dim': BGC_GENERAL_CONFIG['embed_dim'],
        'pool_size': BGC_GENERAL_CONFIG['pool_size'],
        'general_transformer_features': BGC_GENERAL_CONFIG['output_features'],
        'class_transformer_features': BGC_CLASS_CONFIG['output_features'],
        'total_combined_features': X_train_combined.shape[1],
        'batch_size': BATCH_SIZE,
        'max_epochs': MAX_EPOCHS,
        'patience': PATIENCE,
        'min_delta': MIN_DELTA,
        'early_stopping_enabled': True,
        'avg_epochs_saved': round(np.mean(early_stopping_counts), 1) if early_stopping_counts else 0,
        'models_stopped_early': f"{sum(1 for x in early_stopping_counts if x > 0)}/{len(bgc_classes)}",
        'training_date': pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')
    }

    metadata_df = pd.DataFrame([metadata])
    metadata_df.to_csv(os.path.join(OUTPUT_DIR, 'training_metadata.csv'), index=False)

    # Save class information
    class_info = pd.DataFrame({
        'class_index': range(num_classes),
        'class_name': class_names,
        'is_bgc': [0] + [1] * (num_classes - 1),
        'samples_total': np.bincount(y),
        'samples_train': np.bincount(y_train),
        'samples_val': np.bincount(y_val),
        'samples_test': np.bincount(y_test)
    })
    class_info.to_csv(os.path.join(OUTPUT_DIR, 'class_info.csv'), index=False)

    # 10. Create Inference Script
    print("\n📝 Creating inference script...")
    create_inference_script(MODEL_SAVE_DIR, OUTPUT_DIR, bgc_classes)

    # 11. Final Summary
    print("\n" + "="*80)
    print("✅ TRAINING COMPLETE!")
    print("="*80)

    print(f"\n📊 PERFORMANCE SUMMARY:")
    print(f"   Total time: {total_time:.1f} hours")
    print(f"   General transformer: {gen_time:.1f} minutes")
    print(f"   Class transformers: {total_class_time:.1f} minutes total")
    print(f"   Average per class: {total_class_time/len(bgc_classes):.1f} minutes")

    print(f"\n🎯 EARLY STOPPING SUMMARY:")
    print(f"   Models configured for: {MAX_EPOCHS} epochs max")
    print(f"   Early stopping patience: {PATIENCE} epochs")
    if early_stopping_counts:
        avg_saved = np.mean(early_stopping_counts)
        print(f"   Average epochs saved per model: {avg_saved:.1f}")
        print(f"   Models that stopped early: {sum(1 for x in early_stopping_counts if x > 0)}/{len(bgc_classes)}")
    else:
        print(f"   All models trained for full {MAX_EPOCHS} epochs")

    print(f"\n🎯 FEATURE SUMMARY:")
    print(f"   Original features: {X.shape[1]}")
    print(f"   General transformer features: {train_gen_features.shape[1]}")
    print(f"   Each class transformer features: {list(train_class_features.values())[0].shape[1]}")
    print(f"   Total transformer features: {X_train_combined.shape[1]}")

    print(f"\n📁 MODELS SAVED TO: {MODEL_SAVE_DIR}")
    print(f"   • bgc_general_transformer.keras")
    print(f"   • best_bgc_general.keras")
    for class_name in bgc_classes[:5]:  # Show first 5
        safe_name = str(class_name).replace(' ', '_').replace('/', '_')
        print(f"   • bgc_class_transformer_{safe_name}.keras")
        print(f"   • best_bgc_class_{safe_name}.keras")
    if len(bgc_classes) > 5:
        print(f"   • ... and {len(bgc_classes)-5} more")

    print(f"\n📁 FEATURE DATA SAVED TO: {OUTPUT_DIR}")
    print(f"   • X_train_combined.npy ({X_train_combined.shape})")
    print(f"   • X_val_combined.npy ({X_val_combined.shape})")
    print(f"   • X_test_combined.npy ({X_test_combined.shape})")
    print(f"   • training_metadata.csv")
    print(f"   • early_stopping_stats.csv")
    print(f"   • class_info.csv")

    # Quality check
    print(f"\n🧪 QUALITY CHECK:")
    print(f"   Feature shapes consistent: ✓")
    print(f"   No NaN values: {not np.any(np.isnan(X_train_combined))}")
    print(f"   Training range: [{X_train_combined.min():.3f}, {X_train_combined.max():.3f}]")

    print("\n" + "="*80)
    print("🚀 READY FOR CLASSIFIER TRAINING!")
    print("="*80)

def create_inference_script(model_dir, output_dir, bgc_classes):
    """Create inference script for the trained models"""


    script_path = os.path.join(output_dir, 'inference_pipeline.py')
    with open(script_path, 'w') as f:
        f.write(inference_script)

    os.chmod(script_path, 0o755)
    print(f"   ✓ Inference script created: {script_path}")

if __name__ == "__main__":
    main()


#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
XGBoost + 5-Fold CV + AUROC + Test Evaluation
"""

import os
import numpy as np
import pandas as pd
import joblib
import xgboost as xgb

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score
)
from sklearn.preprocessing import label_binarize

# ======================================================
# PATHS
# ======================================================
DATA_DIR = "/home/andromeda_r740/MB/TRAINING_OUTPUT"
MODEL_SAVE = "/home/andromeda_r740/MB/xgboost_final_model.pkl"
OUTPUT_DIR = "/home/andromeda_r740/MB/XGB_RESULTS"

os.makedirs(OUTPUT_DIR, exist_ok=True)

# ======================================================
# LOAD DATA
# ======================================================
print("\nLoading data...")

X_train = np.load(os.path.join(DATA_DIR, "X_train_combined.npy"))
X_val   = np.load(os.path.join(DATA_DIR, "X_val_combined.npy"))
X_test  = np.load(os.path.join(DATA_DIR, "X_test_combined.npy"))

y_train = np.load(os.path.join(DATA_DIR, "y_train.npy"))
y_val   = np.load(os.path.join(DATA_DIR, "y_val.npy"))
y_test  = np.load(os.path.join(DATA_DIR, "y_test.npy"))

# Merge train + val
X = np.vstack([X_train, X_val])
y = np.hstack([y_train, y_val])

num_classes = len(np.unique(y))

# ======================================================
# DEFINE PARAMETERS ONCE ✅
# ======================================================
xgb_params = dict(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="multi:softprob",
    eval_metric="mlogloss",
    tree_method="hist",
    n_jobs=-1,
    random_state=42,
    num_class=num_classes
)

# ======================================================
# STRATIFIED 5-FOLD CV
# ======================================================
print("\nRunning 5-Fold Stratified CV...")

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

metrics_list = []

for fold, (train_idx, val_idx) in enumerate(skf.split(X, y), 1):
    print(f"\nFold {fold}...")

    X_tr, X_va = X[train_idx], X[val_idx]
    y_tr, y_va = y[train_idx], y[val_idx]

    model = xgb.XGBClassifier(**xgb_params)

    model.fit(X_tr, y_tr)

    y_pred = model.predict(X_va)
    y_prob = model.predict_proba(X_va)

    y_va_bin = label_binarize(y_va, classes=np.arange(num_classes))

    acc = accuracy_score(y_va, y_pred)
    prec = precision_score(y_va, y_pred, average='weighted')
    rec = recall_score(y_va, y_pred, average='weighted')
    f1 = f1_score(y_va, y_pred, average='weighted')

    try:
        auc = roc_auc_score(y_va_bin, y_prob, multi_class='ovr', average='weighted')
    except:
        auc = np.nan

    metrics_list.append([acc, prec, rec, f1, auc])

    print(f"Accuracy: {acc:.4f}, F1: {f1:.4f}, AUROC: {auc:.4f}")

# ======================================================
# CV RESULTS
# ======================================================
metrics_array = np.array(metrics_list)

mean_metrics = metrics_array.mean(axis=0)
std_metrics = metrics_array.std(axis=0)

cv_results = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1-score", "AUROC"],
    "Mean": mean_metrics,
    "Std": std_metrics
})

cv_results.to_csv(os.path.join(OUTPUT_DIR, "cv_results.csv"), index=False)

print("\n📊 Cross-Validation Results:")
print(cv_results)

# ======================================================
# FINAL MODEL (same parameters ✅)
# ======================================================
print("\nTraining final model...")

final_model = xgb.XGBClassifier(**xgb_params)
final_model.fit(X, y)

# ======================================================
# TEST EVALUATION
# ======================================================
print("\nEvaluating on test set...")

y_test_pred = final_model.predict(X_test)
y_test_prob = final_model.predict_proba(X_test)

y_test_bin = label_binarize(y_test, classes=np.arange(num_classes))

test_acc = accuracy_score(y_test, y_test_pred)
test_prec = precision_score(y_test, y_test_pred, average='weighted')
test_rec = recall_score(y_test, y_test_pred, average='weighted')
test_f1 = f1_score(y_test, y_test_pred, average='weighted')

try:
    test_auc = roc_auc_score(y_test_bin, y_test_prob, multi_class='ovr', average='weighted')
except:
    test_auc = np.nan

test_results = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1-score", "AUROC"],
    "Value": [test_acc, test_prec, test_rec, test_f1, test_auc]
})

test_results.to_csv(os.path.join(OUTPUT_DIR, "test_results.csv"), index=False)

print("\n📊 Test Results:")
print(test_results)

# ======================================================
# SAVE MODEL
# ======================================================
joblib.dump(final_model, MODEL_SAVE)

print("\n✅ Model saved:", MODEL_SAVE)