# -*- coding: utf-8 -*-
"""GridSearch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kYHCRwYNfcAHHwui7FbUDHKXIZ_h7Ri2
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Dec 28 00:40:47 2025

@author: andromeda_r740
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
FULL TRANSFORMER HYPERPARAMETER GRID SEARCH
----------------------------------------------------------
Phase 1: General Transformer Optimization
Phase 2: Class Transformer Optimization (using most freq class)
"""

import os
import gc
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split, ParameterGrid
from sklearn.preprocessing import StandardScaler, LabelEncoder
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (
    Input, Dense, MultiHeadAttention, LayerNormalization,
    Dropout, GlobalAveragePooling1D, GlobalMaxPooling1D, Reshape,
    Concatenate, Add
)
import tensorflow.keras.backend as K

# ============================
# CONFIGURATION
# ============================
FILE = "/home/andromeda_r740/MB/final_output.csv"
OUTPUT_DIR = "/home/andromeda_r740/MB/GRID_SEARCH_RESULTS_FULL"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Force CPU (remove if you have a stable GPU)
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

# Search Constraints (Speed optimizations)
SEARCH_SUBSET_RATIO = 0.10  # Use 10% of data
SEARCH_EPOCHS = 5           # Quick convergence check
BATCH_SIZE = 256

# ============================
# 1. PARAMETER GRIDS
# ============================

# Grid for General Transformer (Larger Capacity)
GEN_GRID = {
    'embed_dim': [32, 64],
    'num_heads': [2, 4],
    'ff_dim': [16, 32],
    'dropout_rate': [0.2],
    'learning_rate': [0.001],
    'output_features': [256, 512,1024]
}

# Grid for Class Transformer (Lightweight / Optimized)
CLASS_GRID = {
    'embed_dim': [16, 32],       # Smaller dimensions
    'num_heads': [2],            # Keep it simple
    'ff_dim': [8, 16],           # Smaller FFN
    'dropout_rate': [0.2],
    'learning_rate': [0.001],
    'output_features': [128, 256,512]
}

# ============================
# 2. MODEL BUILDERS
# ============================
def build_general_model(config, input_dim):
    """Builds General Transformer (Single Output)"""
    inputs = Input(shape=(input_dim,))
    x = Reshape((input_dim, 1))(inputs)

    x = Dense(config['embed_dim'], activation='relu')(x)
    x = Dropout(config['dropout_rate'])(x)

    attn_output = MultiHeadAttention(num_heads=config['num_heads'], key_dim=config['embed_dim']//config['num_heads'])(x, x)
    x = Add()([x, attn_output])
    x = LayerNormalization()(x)

    avg_pool = GlobalAveragePooling1D()(x)
    max_pool = GlobalMaxPooling1D()(x)
    x = Concatenate()([avg_pool, max_pool])
    x = Dropout(config['dropout_rate'])(x)

    outputs = Dense(config['output_features'], activation='linear')(x)

    model = Model(inputs=inputs, outputs=outputs)
    model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=config['learning_rate']), loss='mse')
    return model

def build_class_model(config, input_dim):
    """Builds Class Transformer (Dual Output: Features + Binary)"""
    inputs = Input(shape=(input_dim,))
    x = Reshape((input_dim, 1))(inputs)

    # Class-specific init simulation
    x = Dense(config['embed_dim'], activation='relu')(x)
    x = Dropout(config['dropout_rate'])(x)

    attn_output = MultiHeadAttention(num_heads=config['num_heads'], key_dim=config['embed_dim'])(x, x)
    x = Add()([x, attn_output])
    x = LayerNormalization()(x)

    # Class transformer usually uses just Max Pooling for speed
    x = GlobalMaxPooling1D()(x)
    x = Dropout(config['dropout_rate'])(x)

    # Dual Outputs
    features = Dense(config['output_features'], activation='relu', name='transformer_output')(x)
    binary = Dense(1, activation='sigmoid', name='binary_output')(features)

    model = Model(inputs=inputs, outputs=[features, binary])

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=config['learning_rate']),
        loss={'transformer_output': 'mse', 'binary_output': 'binary_crossentropy'},
        loss_weights={'transformer_output': 0.2, 'binary_output': 0.8}
    )
    return model

def clear_memory():
    K.clear_session()
    gc.collect()

# ============================
# 3. HELPER: TARGET GENERATOR
# ============================
def get_general_targets(y_data, out_feats, num_classes):
    targets = np.zeros((len(y_data), out_feats))
    for i in range(num_classes):
        mask = (y_data == i)
        if np.any(mask):
            targets[mask, i % out_feats] = 1.0
    return targets

# ============================
# 4. MAIN SEARCH LOOP
# ============================
def main():
    print("="*80)
    print("🚀 FULL TRANSFORMER GRID SEARCH")
    print("="*80)

    # --- LOAD DATA ---
    print("\n📂 Loading data...")
    df = pd.read_csv(FILE)
    label_col = df.columns[-1]
    X = df.drop(columns=[label_col]).values.astype(np.float32)
    le = LabelEncoder()
    y = le.fit_transform(df[label_col].values)
    num_classes = len(le.classes_)

    # --- SUBSET DATA ---
    print(f"   Using {SEARCH_SUBSET_RATIO*100}% of data for search...")
    X_train_full, _, y_train_full, _ = train_test_split(
        X, y, train_size=SEARCH_SUBSET_RATIO, stratify=y, random_state=42
    )
    X_train, X_val, y_train, y_val = train_test_split(
        X_train_full, y_train_full, test_size=0.2, stratify=y_train_full, random_state=42
    )

    # --- SCALE ---
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_val = scaler.transform(X_val)
    input_dim = X_train.shape[1]

    # ==========================================
    # PHASE 1: GENERAL TRANSFORMER
    # ==========================================
    print("\n" + "-"*60)
    print("PHASE 1: Searching General Transformer Parameters")
    print("-"*60)

    gen_grid = list(ParameterGrid(GEN_GRID))
    best_gen_loss = float('inf')
    best_gen_config = None

    for i, params in enumerate(gen_grid):
        print(f"[{i+1}/{len(gen_grid)}] Testing: {params}", end="... ")
        clear_memory()

        try:
            model = build_general_model(params, input_dim)
            y_train_tgt = get_general_targets(y_train, params['output_features'], num_classes)
            y_val_tgt = get_general_targets(y_val, params['output_features'], num_classes)

            h = model.fit(X_train, y_train_tgt, validation_data=(X_val, y_val_tgt),
                          epochs=SEARCH_EPOCHS, batch_size=BATCH_SIZE, verbose=0)

            loss = h.history['val_loss'][-1]
            print(f"Loss: {loss:.5f}")

            if loss < best_gen_loss:
                best_gen_loss = loss
                best_gen_config = params
        except Exception as e:
            print(f"Failed ({e})")

    # ==========================================
    # PHASE 2: CLASS TRANSFORMER
    # ==========================================
    print("\n" + "-"*60)
    print("PHASE 2: Searching Class Transformer Parameters")
    print("-"*60)
    print("ℹ️  Using most frequent class as proxy for optimization")

    # Identify most frequent class
    counts = np.bincount(y_train)
    target_class = np.argmax(counts)
    print(f"   Target Class Index: {target_class} (Count: {counts[target_class]})")

    # Prepare Binary Targets for this class
    y_train_bin = (y_train == target_class).astype(float)
    y_val_bin = (y_val == target_class).astype(float)

    class_grid = list(ParameterGrid(CLASS_GRID))
    best_class_loss = float('inf')
    best_class_config = None

    for i, params in enumerate(class_grid):
        print(f"[{i+1}/{len(class_grid)}] Testing: {params}", end="... ")
        clear_memory()

        try:
            model = build_class_model(params, input_dim)

            # Feature targets (dummy 1.0 for positive class)
            y_train_feat = np.zeros((len(y_train), params['output_features']))
            y_val_feat = np.zeros((len(y_val), params['output_features']))
            y_train_feat[y_train == target_class, 0] = 1.0
            y_val_feat[y_val == target_class, 0] = 1.0

            h = model.fit(
                X_train,
                {'transformer_output': y_train_feat, 'binary_output': y_train_bin},
                validation_data=(X_val, {'transformer_output': y_val_feat, 'binary_output': y_val_bin}),
                epochs=SEARCH_EPOCHS, batch_size=BATCH_SIZE, verbose=0
            )

            # We optimize for the binary classification loss mostly
            loss = h.history['val_binary_output_loss'][-1]
            print(f"BinLoss: {loss:.5f}")

            if loss < best_class_loss:
                best_class_loss = loss
                best_class_config = params
        except Exception as e:
            print(f"Failed ({e})")

    # ==========================================
    # FINAL OUTPUT
    # ==========================================
    print("\n" + "="*80)
    print("🏆 OPTIMIZED CONFIGURATIONS")
    print("="*80)



    print("# ⚡ OPTIMIZED ARCHITECTURES ⚡")
    print("GEN_TRANSFORMER_CONFIG = {")
    print(f"    'input_dim': None,")
    for k, v in best_gen_config.items():
        print(f"    '{k}': {v},")
    print("}")

    print("\nCLASS_TRANSFORMER_CONFIG = {")
    print(f"    'input_dim': None,")
    for k, v in best_class_config.items():
        print(f"    '{k}': {v},")
    print("}")
    print("-" * 40)

    # Save results to CSV for record
    pd.DataFrame([best_gen_config]).to_csv(os.path.join(OUTPUT_DIR, 'best_gen_config.csv'), index=False)
    pd.DataFrame([best_class_config]).to_csv(os.path.join(OUTPUT_DIR, 'best_class_config.csv'), index=False)
    print(f"\nConfigs saved to: {OUTPUT_DIR}")

if __name__ == "__main__":
    main()



#Grid search for XGBoost

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
XGBOOST GRID SEARCH (Transformer Features)

"""

import os
import numpy as np
import pandas as pd
import joblib
import xgboost as xgb

from sklearn.model_selection import train_test_split, ParameterGrid
from sklearn.metrics import f1_score, accuracy_score

# ======================================================
# PATHS
# ======================================================
DATA_DIR = "/home/andromeda_r740/MB/TRAINING_OUTPUT_8thJAN"
OUTPUT_DIR = "/home/andromeda_r740/MB/XGB_GRID_SEARCH"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ======================================================
# SETTINGS (like transformer search)
# ======================================================
SEARCH_SUBSET_RATIO = 0.2
RANDOM_STATE = 42

# ======================================================
# PARAMETER GRID
# ======================================================
XGB_GRID = {
    "n_estimators": [200,400,600],
    "max_depth": [6, 8],
    "learning_rate": [0.05, 0.1],
    "subsample": [0.5,0.8],
    "colsample_bytree": [0.5,0.8]
}

# ======================================================
# LOAD DATA
# ======================================================
print("\n📂 Loading transformer features...")

X = np.load(os.path.join(DATA_DIR, "X_train_combined.npy"))
y = np.load(os.path.join(DATA_DIR, "y_train.npy"))

# ======================================================
# SUBSET (like transformer search)
# ======================================================
print(f"\nUsing {SEARCH_SUBSET_RATIO*100}% data for search...")

X_sub, _, y_sub, _ = train_test_split(
    X, y,
    train_size=SEARCH_SUBSET_RATIO,
    stratify=y,
    random_state=RANDOM_STATE
)

X_train, X_val, y_train, y_val = train_test_split(
    X_sub, y_sub,
    test_size=0.2,
    stratify=y_sub,
    random_state=RANDOM_STATE
)

print("Train:", X_train.shape)
print("Val:", X_val.shape)

# ======================================================
# GRID SEARCH
# ======================================================
print("\n🚀 Running XGBoost Grid Search...")

param_list = list(ParameterGrid(XGB_GRID))

best_score = -1
best_config = None
results = []

for i, params in enumerate(param_list):
    print(f"[{i+1}/{len(param_list)}] Testing: {params}", end="... ")

    try:
        model = xgb.XGBClassifier(
            objective="multi:softprob",
            eval_metric="mlogloss",
            tree_method="hist",
            n_jobs=-1,
            **params
        )

        model.fit(X_train, y_train)

        y_pred = model.predict(X_val)

        acc = accuracy_score(y_val, y_pred)
        f1 = f1_score(y_val, y_pred, average="weighted")

        score = f1  # primary metric

        results.append({
            **params,
            "accuracy": acc,
            "f1_score": f1
        })

        print(f"F1: {f1:.4f}")

        if score > best_score:
            best_score = score
            best_config = params

    except Exception as e:
        print(f"Failed ({e})")

# ======================================================
# SAVE RESULTS
# ======================================================
results_df = pd.DataFrame(results)
results_df.to_csv(os.path.join(OUTPUT_DIR, "xgb_grid_results.csv"), index=False)

pd.DataFrame([best_config]).to_csv(
    os.path.join(OUTPUT_DIR, "best_xgb_config.csv"),
    index=False
)

# ======================================================
# FINAL OUTPUT
# ======================================================
print("\n" + "="*60)
print("🏆 BEST XGBOOST CONFIG")
print("="*60)

print("XGB_CONFIG = {")
for k, v in best_config.items():
    print(f"    '{k}': {v},")
print("}")

print(f"\nBest F1-score: {best_score:.4f}")
print(f"\nSaved results to: {OUTPUT_DIR}")