# -*- coding: utf-8 -*-
"""Shap_Analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YLncAmLlHsLh0HNFvXcEwpcYe-42fTU2
"""

# ======================================================
# Configuration
# ======================================================

N_EXPLAIN = 500
N_BACKGROUND = 400

OUTPUT_DIR = "shap_results_Final"
os.makedirs(OUTPUT_DIR, exist_ok=True)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# ======================================================
# Background Samples
# ======================================================
background = np.array(
    X.iloc[N_EXPLAIN:N_EXPLAIN + N_BACKGROUND],
    dtype=np.float32
)

print(f"Using FIXED background samples: rows {N_EXPLAIN}–{N_EXPLAIN + N_BACKGROUND - 1}")
print("Background shape:", background.shape)

# ======================================================
# Convert Original Features → Transformer Embeddings
# ======================================================
def original_to_emb(X_np):
    return wrapper.transform(X_np)

# ======================================================
# Detect number of classes
# ======================================================
if isinstance(test_pred, list):
    n_classes = len(test_pred)
else:
    n_classes = test_pred.shape[1]

print("Detected number of classes:", n_classes)

# ======================================================
# ============ PER-CLASS SHAP ==========================
# ======================================================
for class_idx, class_name in enumerate(class_names):

    print("\n===================================")
    print(f"Running SHAP for class: {class_name}")
    print("===================================")

    def model_wrapper_class(X_input_numpy):
        X_input = np.array(X_input_numpy, dtype=np.float32)
        emb = original_to_emb(X_input)
        probs = xgboost.predict_proba(emb)

        return probs[:, class_idx]

    explainer = shap.KernelExplainer(
        model_wrapper_class,
        background
    )

    shap_values = explainer.shap_values(
        X_sample_np,
        nsamples=350
    )

    shap_values = np.array(shap_values)
    mean_abs_shap = np.abs(shap_values).mean(axis=0)

    result_df = pd.DataFrame({
        "Feature": X_sample.columns,
        f"MeanAbsSHAP_{class_name}": mean_abs_shap
    }).sort_values(
        f"MeanAbsSHAP_{class_name}",
        ascending=False
    )

    result_df.to_excel(
        os.path.join(OUTPUT_DIR, f"feature_importance_{class_name}.xlsx"),
        index=False
    )

    np.save(
        os.path.join(OUTPUT_DIR, f"shap_values_{class_name}.npy"),
        shap_values
    )

    plt.figure(figsize=(8, 6))
    shap.summary_plot(
        shap_values,
        X_sample,
        feature_names=X_sample.columns,
        plot_type="bar",
        show=False
    )
    plt.title(f"SHAP Feature Importance ({class_name})")
    plt.tight_layout()
    plt.savefig(
        os.path.join(OUTPUT_DIR, f"shap_summary_{class_name}.png")
    )
    plt.close()

    print(f"Finished SHAP for class: {class_name}")

# ======================================================
# ============ OVERALL SHAP ============================
# ======================================================
print("\n===================================")
print("Running Overall SHAP")
print("===================================")

def model_wrapper_overall(X_input_numpy):
    X_input = np.array(X_input_numpy, dtype=np.float32)
    emb = original_to_emb(X_input)
    probs = xgboost.predict_proba(emb)

    return probs.mean(axis=1)

explainer_overall = shap.KernelExplainer(
    model_wrapper_overall,
    background
)

shap_values_overall = explainer_overall.shap_values(
    X_sample_np,
    nsamples=400
)

shap_values_overall = np.array(shap_values_overall)
mean_abs_shap_overall = np.abs(shap_values_overall).mean(axis=0)

overall_df = pd.DataFrame({
    "Feature": X_sample.columns,
    "MeanAbsSHAP_Overall": mean_abs_shap_overall
}).sort_values(
    "MeanAbsSHAP_Overall",
    ascending=False
)

overall_df.to_excel(
    os.path.join(OUTPUT_DIR, "overall_feature_importance.xlsx"),
    index=False
)

np.save(
    os.path.join(OUTPUT_DIR, "shap_values_overall.npy"),
    shap_values_overall
)

plt.figure(figsize=(8, 6))
shap.summary_plot(
    shap_values_overall,
    X_sample,
    feature_names=X_sample.columns,
    plot_type="bar",
    show=False
)
plt.title("Overall SHAP Feature Importance")
plt.tight_layout()
plt.savefig(
    os.path.join(OUTPUT_DIR, "shap_summary_overall.png")
)
plt.close()

print("\nAll SHAP computations complete.")
print("Results saved in:", OUTPUT_DIR)